name:                liquid-flex-hs
version:             0.1.0.0
github:              "githubuser/liquid-flex-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup insistde cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/liquid-flex-hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- mtl
- containers
- transformers
- lens
- HUnit
- singletons
- singletons-th
- parsec
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# TMP - -Wmissing-export-lists
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-imports #TMP

default-extensions:
- LambdaCase
- BlockArguments
- RankNTypes
- NamedFieldPuns
- EmptyDataDeriving
- OverloadedStrings
- TupleSections
- ApplicativeDo
- DeriveFunctor
- DeriveGeneric
- FlexibleInstances

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - liquid-fixpoint
  - deepseq
  - text

executables:
  liquid-flex-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liquid-flex-hs

tests:
  liquid-flex-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liquid-flex-hs
